plugins { id 'dev.architectury.loom-no-remap'; id 'dev.architectury.loom' }
sourceSets { main { java.srcDir rootProject.file('src/main/java'); resources.setSrcDirs([]) } }
dependencies { minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"; compileOnly "net.fabricmc:fabric-loader:${rootProject.loader_version}" }
